window.__KOSHA_DATA=(function(){
"use strict";
const STORAGE="kosha_last_reading_v1";
const LETTER={A:1,B:2,C:3,D:4,E:5,F:6,G:7,H:8,I:9,J:1,K:2,L:3,M:4,N:5,O:6,P:7,Q:8,R:9,S:1,T:2,U:3,V:4,W:5,X:6,Y:7,Z:8};
const VOWELS=new Set(["A","E","I","O","U"]);
const WEST={
Aries:{el:"Fire",planet:"Mars",blurb:"Bold spark energy — you start things and chase the horizon.",vibe:"street"},
Taurus:{el:"Earth",planet:"Venus",blurb:"Steady sensual grounding — beauty, patience, and lasting value.",vibe:"classic"},
Gemini:{el:"Air",planet:"Mercury",blurb:"Curious dual-channel mind — words, wit, and quick pivots.",vibe:"street"},
Cancer:{el:"Water",planet:"Moon",blurb:"Protective emotional tide — home, intuition, deep loyalty.",vibe:"soft"},
Leo:{el:"Fire",planet:"Sun",blurb:"Radiant center-stage warmth — creativity and generous pride.",vibe:"luxe"},
Virgo:{el:"Earth",planet:"Mercury",blurb:"Precise helpful craft — refine, organize, serve with care.",vibe:"minimal"},
Libra:{el:"Air",planet:"Venus",blurb:"Harmonizing aesthetic balance — diplomacy and design eye.",vibe:"classic"},
Scorpio:{el:"Water",planet:"Pluto",blurb:"Intensity with depth — transform, focus, fierce loyalty.",vibe:"dark"},
Sagittarius:{el:"Fire",planet:"Jupiter",blurb:"Expansive explorer spirit — truth-seeking and big-picture joy.",vibe:"adventure"},
Capricorn:{el:"Earth",planet:"Saturn",blurb:"Ambitious mountain climb — structure, legacy, quiet power.",vibe:"minimal"},
Aquarius:{el:"Air",planet:"Uranus",blurb:"Future-facing rebel mind — community, ideas, unconventional cool.",vibe:"tech"},
Pisces:{el:"Water",planet:"Neptune",blurb:"Dreamy empathic flow — imagination, art, soft boundaries.",vibe:"soft"}
};
const CN_ANIMALS=["Rat","Ox","Tiger","Rabbit","Dragon","Snake","Horse","Goat","Monkey","Rooster","Dog","Pig"];
const CN_ELEMENTS=["Wood","Fire","Earth","Metal","Water"];
const CN_TRAITS={Rat:"Quick wit, resourceful, social radar.",Ox:"Reliable strength, patient builder.",Tiger:"Courageous drive, magnetic presence.",Rabbit:"Gentle diplomacy, aesthetic sense.",Dragon:"Ambitious charisma, big vision.",Snake:"Strategic intuition, elegant focus.",Horse:"Independent energy, love of freedom.",Goat:"Creative empathy, artistic taste.",Monkey:"Playful ingenuity, clever solutions.",Rooster:"Sharp presentation, proud detail.",Dog:"Loyal protector, sincere friend.",Pig:"Generous heart, comfort-loving soul."};
const CN_COMPAT={Rat:"Ox & Dragon",Ox:"Rat & Snake",Tiger:"Horse & Dog",Rabbit:"Goat & Pig",Dragon:"Rat & Monkey",Snake:"Ox & Rooster",Horse:"Tiger & Goat",Goat:"Rabbit & Horse",Monkey:"Dragon & Rat",Rooster:"Snake & Ox",Dog:"Tiger & Horse",Pig:"Rabbit & Goat"};
const LIFE={1:"Pioneer — lead with original ideas.",2:"Diplomat — partnership and patience.",3:"Creator — express, inspire, play.",4:"Builder — systems, craft, stability.",5:"Adventurer — change, freedom, curiosity.",6:"Caretaker — nurture, beauty, responsibility.",7:"Seeker — analysis, solitude, insight.",8:"Achiever — power, abundance, stewardship.",9:"Humanitarian — vision, compassion, release.",11:"Illuminator — inspired intuition (master).",22:"Master Builder — large-scale vision (master).",33:"Master Teacher — elevated care (master)."};
const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const LUCKY_DAY={1:"Sunday",2:"Monday",3:"Thursday",4:"Saturday",5:"Wednesday",6:"Friday",7:"Monday",8:"Saturday",9:"Tuesday",11:"Sunday",22:"Saturday",33:"Friday"};
const COLORS={1:[{n:"Crimson",c:"#ef4444"},{n:"Gold",c:"#fbbf24"}],2:[{n:"Silver",c:"#94a3b8"},{n:"Pearl",c:"#e2e8f0"}],3:[{n:"Sky blue",c:"#38bdf8"},{n:"Yellow",c:"#facc15"}],4:[{n:"Forest",c:"#22c55e"},{n:"Navy",c:"#1e3a8a"}],5:[{n:"Turquoise",c:"#2dd4bf"},{n:"Orange",c:"#fb923c"}],6:[{n:"Rose",c:"#fb7185"},{n:"Indigo",c:"#6366f1"}],7:[{n:"Violet",c:"#a78bfa"},{n:"Teal",c:"#14b8a6"}],8:[{n:"Black",c:"#0f172a"},{n:"Deep purple",c:"#6d28d9"}],9:[{n:"Coral",c:"#f97316"},{n:"White",c:"#f8fafc"}],11:[{n:"Silver",c:"#cbd5e1"},{n:"Electric blue",c:"#3b82f6"}],22:[{n:"Charcoal",c:"#334155"},{n:"Bronze",c:"#b45309"}],33:[{n:"Lavender",c:"#c4b5fd"},{n:"Mint",c:"#6ee7b7"}]};
const EL_COLOR={Fire:[{n:"Ember",c:"#f97316"},{n:"Sun gold",c:"#fbbf24"}],Earth:[{n:"Olive",c:"#84cc16"},{n:"Clay",c:"#a16207"}],Air:[{n:"Sky",c:"#38bdf8"},{n:"Cloud",c:"#e2e8f0"}],Water:[{n:"Ocean",c:"#0ea5e9"},{n:"Seafoam",c:"#2dd4bf"}]};
const STYLE={minimal:{label:"Minimal polish",brands:["COS","Uniqlo","Everlane"]},street:{label:"Street energy",brands:["Nike","Supreme vibe","Adidas"]},classic:{label:"Timeless classic",brands:["Ralph Lauren","Brooks Brothers vibe","Massimo Dutti"]},luxe:{label:"Quiet luxury",brands:["The Row vibe","Loro Piana vibe","Hermès energy"]},soft:{label:"Soft romantic",brands:["Sezane","& Other Stories","COS soft"]},dark:{label:"Dark edge",brands:["AllSaints","Rick Owens vibe","Acne Studios"]},adventure:{label:"Adventure ready",brands:["Patagonia","The North Face","Arc'teryx"]},tech:{label:"Tech-forward",brands:["Outlier","Uniqlo Tech","Nike ACG"]}};
const AUTO={minimal:{label:"Reliable EV / clean sedan",ex:["Tesla Model 3 energy","Toyota Prius vibe","Polestar"]},street:{label:"Urban hatch / sporty daily",ex:["VW GTI vibe","Mini Cooper","Honda Civic Type R energy"]},classic:{label:"Elegant sedan / grand tourer",ex:["Mercedes-Benz vibe","Lexus","BMW 5 Series energy"]},luxe:{label:"Statement luxury",ex:["Porsche vibe","Range Rover","Audi A8 energy"]},soft:{label:"Comfort crossover",ex:["Volvo XC40 vibe","Mazda CX-5","Subaru Outback"]},dark:{label:"Sleek performance",ex:["Audi RS vibe","BMW M energy","Genesis"]},adventure:{label:"Adventure SUV",ex:["Jeep vibe","Land Rover Defender energy","Toyota Land Cruiser"]},tech:{label:"Smart EV / gadget car",ex:["Tesla vibe","Hyundai Ioniq","Lucid energy"]}};
const TECH={minimal:{label:"Apple-like polish",ex:["flagship phone","noise-cancelling buds","clean laptop"]},street:{label:"Android flexibility",ex:["customizable phone","wireless earbuds","gaming handheld"]},classic:{label:"Reliable everyday kit",ex:["midrange phone","smartwatch","solid laptop"]},luxe:{label:"Premium creator stack",ex:["pro laptop","mirrorless camera","hi-fi headphones"]},soft:{label:"Gentle wellness tech",ex:["e-ink reader","sleep tracker","soft lighting"]},dark:{label:"Pro creator tools",ex:["editing workstation","mechanical keyboard","studio monitors"]},adventure:{label:"Rugged field gear",ex:["action camera","GPS watch","power bank"]},tech:{label:"Builder / hacker kit",ex:["dev laptop","smart home hub","VR / spatial"]}};
const GEM_NOTE={1:"Spark of beginnings — name energy that initiates.",2:"Cooperative resonance — names that soften edges.",3:"Expressive frequency — playful communication signal.",4:"Structural tone — names that prefer foundations.",5:"Dynamic pulse — restless curious name vibe.",6:"Harmonic care — nurturing sound signature.",7:"Mystic overtone — introspective name echo.",8:"Authority chord — ambitious material drive.",9:"Universal hum — broad compassionate reach."};
const NUDGE_BASE={
1:["Lead a small start today.","Own your idea this morning.","Channel grit into one sprint.","Pitch something bold.","Take initiative before noon.","Start fresh after a reset.","Rest, then reassert direction."],
2:["Offer patience in partnership.","Listen twice before you reply.","Balance give-and-take carefully.","Collaborate; don't go solo.","Seek harmony over being right.","Soft diplomacy wins today.","Nurture bonds over tasks."],
3:["Share a creative spark lightly.","Write or sketch for 15 minutes.","Speak up with humor, not heat.","Celebrate a small win out loud.","Play — joy is productive too.","Social energy is your fuel.","Create for pleasure, not metrics."],
4:["Tidy one system; feel the calm.","Schedule the needed task.","Build a checklist and finish it.","Organize files or finances.","Steady as Saturn — keep going.","Finish what you nearly completed.","Restore order at a gentle pace."],
5:["Take a short detour — novelty fuels you.","Change your route or playlist.","Move your body — shake restlessness.","Learn a micro-skill online.","Say yes to a spontaneous invite.","Freedom day — explore lightly.","Wander without a plan a little."],
6:["Check on someone you care for.","Beautify a corner of your space.","Cook or care for your circle.","Host or invite connection.","Tend home or health rituals.","Romance beauty into the evening.","Self-care is not selfish today."],
7:["Protect quiet time for insight.","Read something dense and rewarding.","Study a pattern you've noticed.","Ask a deeper question.","Journal insights privately.","Unplug an hour for clarity.","Sit with a mystery — don't force."],
8:["Make one decisive energy move.","Review goals without harshness.","Negotiate firmly but fairly.","Track progress numbers honestly.","Claim credit you've earned.","Invest attention where it warms.","Review abundance with gratitude."],
9:["Release something outdated with grace.","Donate or declutter one item.","Forgive a tiny old friction.","Volunteer a helpful gesture.","Widen your circle of kindness.","Close a chapter gracefully.","Serve a cause bigger than you."],
11:["Trust a flash of intuition — jot it.","Meditate on a single intention.","Notice synchronicities today.","Share an inspired idea gently.","Follow a gut redirect.","Capture a sudden insight.","Dream while awake — then note it."],
22:["Sketch a bigger plan in tiny steps.","Align calendar with long vision.","Lay bricks on a big project.","Map milestones for a dream.","Commit to the long game.","Blueprint tomorrow's build.","Stabilize foundations over flash."],
33:["Teach or soothe with soft words.","Offer encouragement freely.","Hold space for someone's feelings.","Create something that comforts.","Mentor someone quietly.","Spread calm wherever you walk.","Love as practice, not performance."]
};
const NUDGES=Object.fromEntries([0,1,2,3,4,5,6].map(d=>[d,Object.fromEntries(Object.entries(NUDGE_BASE).map(([k,arr])=>[+k,arr[d]]))]));
return {STORAGE,LETTER,VOWELS,WEST,CN_ANIMALS,CN_ELEMENTS,CN_TRAITS,CN_COMPAT,LIFE,DAYS,LUCKY_DAY,COLORS,EL_COLOR,STYLE,AUTO,TECH,GEM_NOTE,NUDGES};
})();
